import { Destination } from '@/types/types';

export const mockDestinations: Destination[] = [
  {
    destinationId: 1,
    destinationName: 'Paris',
    normalizedName: 'paris',
    latitude: 48.8566,
    longitude: 2.3522,
    description: 'The capital city of France, known for the Eiffel Tower.',
    country: 'France',
    created_at: '2022-01-01',
    bestTimeToVisit: 'Spring',
    averageTemperatureLow: '7°C',
    averageTemperatureHigh: '20°C',
    popularActivities: 'Sightseeing, Museums, Walking tours',
    travelTips: 'Book tickets for attractions in advance.',
    nearbyAttractions: 'Louvre Museum, Notre-Dame Cathedral',
    transportationOptions: 'Metro, Bus, Taxi',
    accessibilityInfo: 'Most areas are accessible for wheelchair users.',
    officialLanguage: 'French',
    currency: 'Euro (€)',
    localCuisine: 'Baguettes, Croissants, Wine',
    costLevel: 'High',
    safetyRating: 'Medium',
    culturalSignificance: 'Paris has been a major cultural center of Europe for centuries.',
  },
  {
    destinationId: 2,
    destinationName: 'New York',
    normalizedName: 'new-york',
    latitude: 40.7128,
    longitude: -74.006,
    description: 'The largest city in the United States, famous for Times Square.',
    country: 'USA',
    created_at: '2022-01-01',
    bestTimeToVisit: 'Fall',
    averageTemperatureLow: '10°C',
    averageTemperatureHigh: '25°C',
    popularActivities: 'Broadway shows, Statue of Liberty, Central Park',
    travelTips: 'Avoid peak tourist times for better experiences.',
    nearbyAttractions: 'Empire State Building, Central Park',
    transportationOptions: 'Subway, Bus, Taxi',
    accessibilityInfo:
      'Most attractions are accessible, with subway elevators available at many stations.',
    officialLanguage: 'English',
    currency: 'USD ($)',
    localCuisine: 'Pizza, Bagels, Hot Dogs',
    costLevel: 'High',
    safetyRating: 'Medium',
    culturalSignificance: 'New York is considered the cultural capital of the world.',
  },
];

export const mockTokyo: Destination[] = [
  {
    destinationId: 3,
    destinationName: 'Tokyo, Japan',
    normalizedName: 'tokyo',
    latitude: 35.6762,
    longitude: 139.6503,
    description:
      'Tokyo is the capital of Japan, known for its modern architecture, shopping, and food scene.',
    country: 'Japan',
    created_at: '2024-01-01',
    bestTimeToVisit: 'Spring (March to May) and Autumn (September to November)',
    averageTemperatureLow: '5°C',
    averageTemperatureHigh: '15°C',
    popularActivities: 'Visit Tokyo Tower, Explore Shibuya, Enjoy sushi',
    travelTips: 'Purchase a rail pass for convenient travel.',
    nearbyAttractions: 'Mount Fuji, Hakone, Nikko',
    transportationOptions: 'Subway, Bullet trains, Buses',
    accessibilityInfo: 'Most public transport and tourist attractions are wheelchair accessible.',
    officialLanguage: 'Japanese',
    currency: 'Japanese Yen (¥)',
    localCuisine: 'Sushi, Ramen, Tempura',
    costLevel: 'Moderate',
    safetyRating: 'Very High',
    culturalSignificance: 'Tokyo is a blend of traditional and modern Japanese culture.',
  },
];

export const mockTokyoObj: Destination = {
  destinationId: 3,
  destinationName: 'Tokyo, Japan',
  normalizedName: 'tokyo',
  latitude: 35.6762,
  longitude: 139.6503,
  description:
    'Tokyo is the capital of Japan, known for its modern architecture, shopping, and food scene.',
  country: 'Japan',
  created_at: '2024-01-01',
  bestTimeToVisit: 'Spring (March to May) and Autumn (September to November)',
  averageTemperatureLow: '5°C',
  averageTemperatureHigh: '15°C',
  popularActivities: 'Visit Tokyo Tower, Explore Shibuya, Enjoy sushi',
  travelTips: 'Purchase a rail pass for convenient travel.',
  nearbyAttractions: 'Mount Fuji, Hakone, Nikko',
  transportationOptions: 'Subway, Bullet trains, Buses',
  accessibilityInfo: 'Most public transport and tourist attractions are wheelchair accessible.',
  officialLanguage: 'Japanese',
  currency: 'Japanese Yen (¥)',
  localCuisine: 'Sushi, Ramen, Tempura',
  costLevel: 'Moderate',
  safetyRating: 'Very High',
  culturalSignificance: 'Tokyo is a blend of traditional and modern Japanese culture.',
};
