import { Destination } from '@/types/types';

export const mockDestinations: Destination[] = [
  {
    destination_id: 1,
    destination_name: 'Paris',
    latitude: 48.8566,
    longitude: 2.3522,
    description: 'The capital city of France, known for the Eiffel Tower.',
    country: 'France',
    created_at: '2022-01-01',
    best_time_to_visit: 'Spring',
    average_temperature_low: '7°C',
    average_temperature_high: '20°C',
    popular_activities: 'Sightseeing, Museums, Walking tours',
    travel_tips: 'Book tickets for attractions in advance.',
    nearby_attractions: 'Louvre Museum, Notre-Dame Cathedral',
    transportation_options: 'Metro, Bus, Taxi',
    accessibility_info: 'Most areas are accessible for wheelchair users.',
    official_language: 'French',
    currency: 'Euro (€)',
    local_cuisine: 'Baguettes, Croissants, Wine',
    cost_level: 'High',
    safety_rating: 'Medium',
    cultural_significance: 'Paris has been a major cultural center of Europe for centuries.',
  },
  {
    destination_id: 2,
    destination_name: 'New York',
    latitude: 40.7128,
    longitude: -74.006,
    description: 'The largest city in the United States, famous for Times Square.',
    country: 'USA',
    created_at: '2022-01-01',
    best_time_to_visit: 'Fall',
    average_temperature_low: '10°C',
    average_temperature_high: '25°C',
    popular_activities: 'Broadway shows, Statue of Liberty, Central Park',
    travel_tips: 'Avoid peak tourist times for better experiences.',
    nearby_attractions: 'Empire State Building, Central Park',
    transportation_options: 'Subway, Bus, Taxi',
    accessibility_info:
      'Most attractions are accessible, with subway elevators available at many stations.',
    official_language: 'English',
    currency: 'USD ($)',
    local_cuisine: 'Pizza, Bagels, Hot Dogs',
    cost_level: 'High',
    safety_rating: 'Medium',
    cultural_significance: 'New York is considered the cultural capital of the world.',
  },
];
